### ISSUE TITLE
How to set up network ports with this application?

### ISSUE THREAD

**Issue by CRC32EX** [issy-s16/conoha#8]
# Question
How to set up network ports with this application?

# Steps to reproduce this issue
1. Create new VPS instance
```
# CentOS 8.0 20GB / 512MB
$ conoha compute vm create \
  -i 40da3c94-df97-4f66-9ae0-ca41bc9720ac \
  -f d92b02ce-9a4f-4544-8d7f-ae8380bc08e7 \
  --password MyP@ssword \
  -n myserver001
```

2. Connect to VPS
```
$ ssh root@ip_address
ssh: connect to host ip_address port 22: Resource temporarily unavailable
```

# Possible solution
- Set up netowork ports properties to allowed.

![](https://user-images.githubusercontent.com/25629617/71792656-e9835e00-307c-11ea-982f-f93613c0c5f2.png)

**Comment by CRC32EX** [comment]
# Solution
I found solution.
Use `-g` or `--group-names` option.

|Security group name|Detail|
|:--|:--|
|gncs-ipv4-all|Allow all IPv4 ports|
|gncs-ipv6-all|Allow all IPv6 ports|

### Example.
```
# CentOS 8.0 20GB / 512MB
$ conoha compute vm create \
  -i 40da3c94-df97-4f66-9ae0-ca41bc9720ac \
  -f d92b02ce-9a4f-4544-8d7f-ae8380bc08e7 \
  --password MyP@ssword \
  -n myserver001 \
  -g gncs-ipv4-all
```

### Reference
- https://github.com/hironobu-s/conoha-net

# Problem
We can't set multiple `-g` or `--group-names` options.

### Example.
The first `-g gncs-ipv4-all` parameters is ignored.
```
# CentOS 8.0 20GB / 512MB
$ conoha compute vm create \
  -i 40da3c94-df97-4f66-9ae0-ca41bc9720ac \
  -f d92b02ce-9a4f-4544-8d7f-ae8380bc08e7 \
  --password MyP@ssword \
  -n myserver001 \
  -g gncs-ipv4-all \
  -g gncs-ipv6-all
```

**Comment by CRC32EX** [comment]
Please merge & publish to PyPI.
https://github.com/giginc/conoha/pull/9

![image](https://user-images.githubusercontent.com/25629617/71794542-5ac70f00-3085-11ea-8aaf-1dd202f1422f.png)

![image](https://user-images.githubusercontent.com/25629617/71794597-99f56000-3085-11ea-9c19-800440c97caa.png)

![image](https://user-images.githubusercontent.com/25629617/71794643-cc9f5880-3085-11ea-8568-3ca82d0e5753.png)

**Comment by issys16** [comment]
@CRC32EX Thank you. Released.
